//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakOtomasyonManisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class emlakTipiTablo
    {
        public emlakTipiTablo()
        {
            this.evler = new HashSet<evler>();
        }
    
        public int id { get; set; }
        public string emlakTipi { get; set; }
    
        public virtual ICollection<evler> evler { get; set; }
    }
}
