//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakOtomasyonManisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string adSoyad { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> sonGirisTarihi { get; set; }
        public Nullable<int> girisSayisi { get; set; }
        public string yetki { get; set; }
        public string ePosta { get; set; }
    }
}
